add 3 FPS games to the list
michelpereira/awesome-open-source-games pull request #7
Opened 2022-02-18 16:17 UTC by Tx-Charlie

add:
* Red Eclipse
* Urban Terror
* Darkest Hour

2022-02-20 21:33 UTC, michelpereira commented
Hi, @Tx-Charlie .
Based on the guidelines here it goes my recommendations for the descriptions:
**Redeclipse:** Fun-filled new take on the first person arena shooter, featuring parkour, impulse boosts, and more.
**Urban terror:** Free multiplayer first person shooter that will run on any Quake III Arena compatible engine.
**Darkest Hour:** World War 2 online multiplayer tactical shooter based on Red Orchestra: Ostfront.

Thanks.

2022-02-20 21:36 UTC, michelpereira requested changes

2022-02-20 21:36 UTC, michelpereira commented on README.md
> +- [Red Eclipse](https://github.com/redeclipse) - A fun-filled new take on the first person arena shooter, featuring parkour, impulse boosts, and more.
`- [Red Eclipse](https://github.com/redeclipse) - Fun-filled new take on the first person arena shooter, featuring parkour, impulse boosts, and more.`

2022-02-20 21:40 UTC, michelpereira commented
@Tx-Charlie , I did some comments and please let me know when you submit again.

2022-02-20 23:57 UTC, Tx-Charlie commented
> @Tx-Charlie , I did some comments and please let me know when you submit again.

Ok, done, removed the `A` in `red eclipse` 's description.

2022-02-21 12:47 UTC, michelpereira commented
> > @Tx-Charlie , I did some comments and please let me know when you submit again.
> 
> Ok, done, removed the `A` in `red eclipse` 's description.

Hi, there. Did you see the other one comments that I made?

2022-02-21 12:47 UTC, michelpereira approved these changes

2022-02-21 12:48 UTC, michelpereira requested changes
- [Urban Terror](https://github.com/FrozenSand/UrbanTerror4) - Free multiplayer first person shooter that will run on any Quake III Arena compatible engine.

2022-02-21 12:49 UTC, michelpereira requested changes
`- [Darkest Hour](https://github.com/DarklightGames/DarkestHour) - World War 2 online multiplayer tactical shooter based on Red Orchestra: Ostfront.`

2022-02-21 12:52 UTC, Tx-Charlie commented on README.md
> +- [Darkest Hour](https://github.com/DarklightGames/DarkestHour) A World War 2 online multiplayer tactical shooter based on Tripwire Interactive’s award winning game Red Orchestra: Ostfront. (must own
> > > @Tx-Charlie , I did some comments and please let me know when you submit again.
> > 
> > 
> > Ok, done, removed the `A` in `red eclipse` 's description.
> 
> Hi, there. Did you see the other one comments that I made?

oops, sry, all fixed now.

2022-02-21 13:10 UTC, michelpereira approved these changes

2022-02-21 13:10 UTC, michelpereira approved these changes

2022-02-21 13:13 UTC, michelpereira requested changes
Sorry but there's a dash missing, please update to:
`- [Darkest Hour](https://github.com/DarklightGames/DarkestHour) - World War 2 online multiplayer tactical shooter based on Red Orchestra: Ostfront.`

2022-02-21 13:16 UTC, merged

2022-02-21 13:16 UTC, Tx-Charlie commented
oops, sry